### ISSUE TITLE
[QUESTION] Will this package support Laravel 6?

### ISSUE THREAD

**Issue by 7ard1grad3** [nikazooz/laravel-simplesheet#2]
Hello, 

Will this package support Laravel 6.0? 
May we have any estimation if it is? 

Thanks

**Comment by nikazooz** [comment]
Hi @sheidin 
I've just tagged version 1.1.0 with support for Laravel 6

https://github.com/nikazooz/laravel-simplesheet/releases/tag/1.1.0

Cheers :slightly_smiling_face:
