### ISSUE TITLE
Error of laravel-simplesheet in Laravel 8

### ISSUE THREAD

**Issue by whernandez0989** [nikazooz/laravel-simplesheet#3]
### Prerequisites

* [ x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Simplesheet.
* [ x ] Checked that your issue isn't already filed.
* [ x  Checked if no PR was submitted that fixes this problem.

### Versions

* PHP version: 7.4
* Laravel version: 8
* Package version: 1.2.0

### Steps to Reproduce
hi, when i run the line
composer require nikazooz / laravel-simplesheet

**Expected behavior:**

download correctly

**Actual behavior:**

Root composer.json requires nikazooz/laravel-simplesheet ^1.2 -> satisfiable by nikazooz/laravel-simplesheet[1.2.0].
nikazooz/laravel-simplesheet 1.2.0 requires box/spout ^2.7 -> found box/spout[v2.7.0, v2.7.1, v2.7.2, v2.7.3] but it conflicts with your root composer.json require (^3.2).

### Additional Information

N/A

**Comment by nikazooz** [comment]
I've released version 1.3.0 that adds support for Laravel 8. However, you might still experience version conflicts with `box/spout`. Based on the error I guess you already require version 3 of it in your project and, unfortunately, using version 3 with this is not as straight forward as bumping required version for the package, as it has some breaking changes compared to version 2.

**Comment by whernandez0989** [comment]
how could i help? friend

**Comment by nikazooz** [comment]
I've implemented support for Box Spout 3 and released version 2.0.0. This package's API was not changed. Happy coding!
